### ISSUE TITLE
Panneaux d'affichage libre / panneau administratifs

### ISSUE THREAD

**Issue by Phyks** [osmontrouge/osm2opendata#1]
Voir https://data.montreuil.fr/explore/dataset/panneaux-daffichage-libre/

Quel tagging?

**Comment by francois2metz** [comment]
Ceux que j'ai taggé sont en `advertising=event` http://overpass-turbo.eu/s/L5N Ca reste encore un peu limite en nombre ;)

**Comment by Phyks** [comment]
On en a pas mal taggé avec d'autres valeurs d'advertising: https://overpass-turbo.eu/s/L6r. Une dizaine en tout je crois. Il faudrait qu'on se mette d'accord sur un tagging pour éditer le wiki et les corriger déjà :)
